<?php
# digraph-project-core/files/index.php => web/index.php

# SITE OWNERS: DO NOT EDIT THIS FILE
# It is managed by digraph-project-core and Composer
# Its contents will be overwritten on composer install/update

# set $SITE_PATH so it's available for bootstrapping
$SITE_PATH = realpath(__DIR__.'/..');

# include digraph bootstrapping file so it can do all the work
require $SITE_PATH.'/digraph/core/digraph.php';
